# Generated by Django 4.2.5 on 2023-09-29 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime.now)),
                ('date_of_death', models.DateTimeField(default=datetime.datetime.now)),
                ('alive', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('page', models.PositiveIntegerField(default=3)),
                ('year_of_invented', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.PositiveIntegerField(default=500)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.authormodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categorymodel')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AddField(
            model_name='authormodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categorymodel'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
